services:
  backend:
    build:
      context: ./falcon_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      kibana:
        condition: service_healthy
    links:
      - elasticsearch
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://backend:8000 >/dev/null || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3

  frontend-y:
    build:
      context: ./falcon_frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      backend:
        condition: service_healthy
    links:
      - elasticsearch

  elasticsearch:
    image: bitnami/elasticsearch:7.17.12
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms750m -Xmx750m  # otherwise exit with code 137 meaning OOM kill
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail elasticsearch:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3


  kibana:
    image: "docker.elastic.co/kibana/kibana:7.17.12"
    depends_on:
      elasticsearch:
        condition: service_healthy
    links:
      - elasticsearch
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    ports:
      - "5601:5601"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent -f -LI kibana:5601 || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 10

  logstash:
    image: docker.elastic.co/logstash/logstash:8.2.0
    restart: always
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    ports:
      - "5959:5959"
    environment:
      - STDOUT=true
    volumes:
      - ./logstash.conf:/etc/logstash/conf.d/logstash.conf:ro
    command: logstash -f /etc/logstash/conf.d/logstash.conf

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.17.12
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    volumes:
      - metricbeat-data01:/usr/share/metricbeat/data

  initialize:
    image: "curlimages/curl:7.80.0"
    command: >
      sh -c '
        sh /usr/local/bin/kibana_init.sh
      '
    depends_on:
      - elasticsearch
      - kibana
    volumes:
      - ./kibana_init.sh:/usr/local/bin/kibana_init.sh


volumes:
  metricbeat-data01:
    driver: local
