services:
  backend:
    build:
      context: ./falcon_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://backend:8000 >/dev/null || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./falcon_frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      backend:
        condition: service_healthy
    links:
      - backend
