# Generated by Django 5.0.7 on 2024-07-09 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graph_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GraphMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("autonomy", models.IntegerField()),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departure_node",
                        to="graph_app.node",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destination_node",
                        to="graph_app.node",
                    ),
                ),
            ],
        ),
    ]
