# Generated by Django 5.0.7 on 2024-07-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graph_app", "0002_graphmetadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="BountyHunter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.IntegerField()),
                ("planet", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Empire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("countdown", models.IntegerField()),
                (
                    "bounty_hunters",
                    models.ManyToManyField(
                        related_name="empires", to="graph_app.bountyhunter"
                    ),
                ),
            ],
        ),
    ]
